/**
 * Controlled Android project provider.
 *
 * Scaffolds new Android projects from reviewed, token-only templates and
 * inspects existing project roots. Templates live under
 * `templates/android/<id>/` as `.tpl` files and carry no remote scripts,
 * credentials, local paths, wrapper JAR, or binary files. The only tokens
 * replaced are the declared set below; any unresolved token after substitution
 * is a template bug and fails creation.
 *
 * The Gradle wrapper is generated by an injected `generateWrapper` callback.
 * In production this runs the trusted Gradle distribution (`wrapper
 * --gradle-version <v> --distribution-type bin`) and writes the catalog
 * `distributionSha256Sum` into `gradle-wrapper.properties`; in tests a fake
 * writes text-only wrapper files. The provider never downloads a wrapper JAR
 * itself and rejects a template that ships one.
 */

import fs from "node:fs";
import path from "node:path";
import { randomBytes } from "node:crypto";
import type {
  DevelopmentProjectProvider,
  DevelopmentEcosystem,
  ProjectCreateRequest,
  ProjectCreateResult,
  ProjectInspection,
  ProjectTemplateSummary,
  ProjectTemplateProfile,
} from "../projects/types.js";
import { PACKAGE_ID_REGEX } from "./types.js";

export interface AndroidProjectProviderOptions {
  /** Root directory of the Android templates tree. */
  templatesRoot?: string;
  /**
   * Generate the Gradle wrapper inside the staged project. Returns the
   * `distributionSha256Sum` written into `gradle-wrapper.properties`.
   */
  generateWrapper: (
    stagingDir: string,
    gradleVersion: string,
  ) => { distributionSha256Sum: string };
}

interface AndroidTemplate {
  id: string;
  displayName: string;
  description: string;
  dir: string;
}

const PROJECT_NAME_REGEX = /^[A-Za-z][A-Za-z0-9_-]{0,63}$/;

const TOKEN_RE = /__[A-Z0-9_]+__/g;

const TEMPLATES: readonly AndroidTemplate[] = [
  {
    id: "kotlin-basic",
    displayName: "Kotlin — Basic",
    description: "A minimal single-activity Kotlin Android project.",
    dir: "kotlin-basic",
  },
  {
    id: "compose-basic",
    displayName: "Kotlin — Jetpack Compose",
    description: "A single-activity Jetpack Compose Android project.",
    dir: "compose-basic",
  },
];

export class AndroidProjectProvider implements DevelopmentProjectProvider {
  readonly ecosystem: DevelopmentEcosystem = "android";
  private readonly templatesRoot: string;
  private readonly generateWrapper: AndroidProjectProviderOptions["generateWrapper"];

  constructor(options: AndroidProjectProviderOptions) {
    this.templatesRoot =
      options.templatesRoot ?? path.resolve(process.cwd(), "templates/android");
    this.generateWrapper = options.generateWrapper;
  }

  templates(): ProjectTemplateSummary[] {
    return TEMPLATES.map((t) => ({
      id: t.id,
      displayName: t.displayName,
      description: t.description,
    }));
  }

  async inspect(root: string): Promise<ProjectInspection> {
    const gradleFiles: string[] = [];
    for (const name of ["settings.gradle.kts", "build.gradle.kts", "app/build.gradle.kts"]) {
      const full = path.join(root, name);
      if (fs.existsSync(full)) gradleFiles.push(name);
    }
    let manifestPackage: string | undefined;
    const manifest = path.join(root, "app/src/main/AndroidManifest.xml");
    if (fs.existsSync(manifest)) {
      const text = fs.readFileSync(manifest, "utf8");
      const match = text.match(/package="([^"]+)"/);
      if (match) manifestPackage = match[1];
    }
    return { ecosystem: "android", root, gradleFiles, manifestPackage };
  }

  async create(
    request: ProjectCreateRequest,
    stagingRoot: string,
  ): Promise<ProjectCreateResult> {
    this.validateRequest(request);
    const template = TEMPLATES.find((t) => t.id === request.templateId);
    if (!template) {
      throw new Error(`unknown android template id: ${request.templateId}`);
    }
    const templateDir = path.join(this.templatesRoot, template.dir);
    if (!fs.existsSync(templateDir)) {
      throw new Error(`template directory missing: ${templateDir}`);
    }

    const stagingDir = path.join(stagingRoot, `android-${randomBytes(8).toString("hex")}`);
    fs.mkdirSync(stagingDir, { recursive: true });

    try {
      this.stageTemplate(templateDir, stagingDir, request);
      const { distributionSha256Sum } = this.generateWrapper(
        stagingDir,
        request.profile.gradle,
      );
      this.ensureWrapperChecksum(stagingDir, distributionSha256Sum, request.profile.gradle);
      this.refuseNonemptyDestination(request.destination);
      this.atomicMove(stagingDir, request.destination);
    } catch (err) {
      fs.rmSync(stagingDir, { recursive: true, force: true });
      throw err;
    }

    const files = walk(request.destination).map((f) =>
      path.relative(request.destination, f).replace(/\\/g, "/"),
    );
    return { root: request.destination, files };
  }

  private validateRequest(request: ProjectCreateRequest): void {
    if (!PROJECT_NAME_REGEX.test(request.projectName)) {
      throw new Error(`invalid project name: ${request.projectName}`);
    }
    if (!PACKAGE_ID_REGEX.test(request.packageId)) {
      throw new Error(`invalid package id: ${request.packageId}`);
    }
    const p = request.profile;
    if (
      !Number.isInteger(p.compileSdk) || p.compileSdk < 1 ||
      !Number.isInteger(p.minSdk) || p.minSdk < 1 ||
      !Number.isInteger(p.targetSdk) || p.targetSdk < 1 ||
      p.minSdk > p.targetSdk
    ) {
      throw new Error("invalid sdk profile");
    }
  }

  private stageTemplate(
    templateDir: string,
    stagingDir: string,
    request: ProjectCreateRequest,
  ): void {
    const tokens = this.tokenMap(request);
    for (const rel of walkRel(templateDir)) {
      const transformedPath = this.applyTokens(rel, tokens).replace(/\.tpl$/, "");
      const src = path.join(templateDir, rel);
      const dest = path.join(stagingDir, transformedPath);
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      if (rel.endsWith(".tpl")) {
        const content = fs.readFileSync(src, "utf8");
        const replaced = this.applyTokens(content, tokens);
        this.assertNoUnresolvedTokens(replaced, rel);
        fs.writeFileSync(dest, replaced);
      } else {
        // Non-template binary asset: rejected (templates carry no binaries).
        throw new Error(`template ships non-template file: ${rel}`);
      }
    }
  }

  private tokenMap(request: ProjectCreateRequest): Map<string, string> {
    const p = request.profile;
    const map = new Map<string, string>([
      ["__PROJECT_NAME__", request.projectName],
      ["__PACKAGE_ID__", request.packageId],
      ["__PACKAGE_PATH__", request.packageId.replace(/\./g, "/")],
      ["__COMPILE_SDK__", String(p.compileSdk)],
      ["__MIN_SDK__", String(p.minSdk)],
      ["__TARGET_SDK__", String(p.targetSdk)],
      ["__AGP_VERSION__", p.agp],
      ["__KOTLIN_VERSION__", p.kotlin],
      ["__GRADLE_VERSION__", p.gradle],
    ]);
    if (p.composeCompiler) {
      map.set("__COMPOSE_COMPILER_VERSION__", p.composeCompiler);
    }
    return map;
  }

  private applyTokens(value: string, tokens: Map<string, string>): string {
    return value.replace(TOKEN_RE, (m) => tokens.get(m) ?? m);
  }

  private assertNoUnresolvedTokens(content: string, rel: string): void {
    const leftover = content.match(TOKEN_RE);
    if (leftover) {
      throw new Error(`unresolved template token(s) in ${rel}: ${leftover.join(", ")}`);
    }
  }

  private ensureWrapperChecksum(
    stagingDir: string,
    sha256: string,
    gradleVersion: string,
  ): void {
    const propsPath = path.join(stagingDir, "gradle/wrapper/gradle-wrapper.properties");
    if (!fs.existsSync(propsPath)) {
      // generateWrapper did not create it; write a minimal one.
      fs.mkdirSync(path.dirname(propsPath), { recursive: true });
      fs.writeFileSync(
        propsPath,
        `distributionUrl=https\\://services.gradle.org/distributions/gradle-${gradleVersion}-bin.zip\n` +
          `distributionSha256Sum=${sha256}\n`,
      );
      return;
    }
    let text = fs.readFileSync(propsPath, "utf8");
    if (!/^distributionSha256Sum=/m.test(text)) {
      text = text.trimEnd() + `\ndistributionSha256Sum=${sha256}\n`;
      fs.writeFileSync(propsPath, text);
    }
  }

  private refuseNonemptyDestination(destination: string): void {
    if (fs.existsSync(destination)) {
      const entries = fs.readdirSync(destination);
      if (entries.length > 0) {
        throw new Error(`destination not empty: ${destination}`);
      }
    }
  }

  private atomicMove(stagingDir: string, destination: string): void {
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.renameSync(stagingDir, destination);
  }
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

function walkRel(dir: string): string[] {
  return walk(dir).map((f) => path.relative(dir, f).replace(/\\/g, "/"));
}
