/**
 * Install a reviewed Gradle Wrapper into a staged Android project.
 *
 * The assets are copied from the repository, never downloaded at request
 * time and never generated by a caller-selected executable. Every byte is
 * checked against source-controlled hashes from Gradle's verified v8.10.2
 * tag before it enters the project. The distribution URL/checksum remains
 * bound to the reviewed development component catalog.
 */

import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import type { DevelopmentCatalog } from "../environment/types.js";

export const REVIEWED_GRADLE_WRAPPER_VERSION = "8.10.2";

const REVIEWED_FILES = [
  {
    source: "gradlew",
    destination: "gradlew",
    size: 8784,
    sha256: "9cbbb4d68ff7fb5211c4d58f598ac9d8664c05fdcd1e5f59b7f2c3ac1ee00af0",
  },
  {
    source: "gradlew.bat",
    destination: "gradlew.bat",
    size: 2894,
    sha256: "0f3ed8f03b50934cb8c48b15a470d5c20a30a5385825e48b55bcc8ea3d8f8e18",
  },
  {
    source: "gradle-wrapper.jar",
    destination: "gradle/wrapper/gradle-wrapper.jar",
    size: 43583,
    sha256: "2db75c40782f5e8ba1fc278a5574bab070adccb2d21ca5a6e5ed840888448046",
  },
] as const;

function sha256(buffer: Buffer): string {
  return createHash("sha256").update(buffer).digest("hex");
}

export interface ReviewedGradleWrapperOptions {
  assetsRoot?: string;
}

export function installReviewedGradleWrapper(
  stagingDir: string,
  gradleVersion: string,
  catalog: DevelopmentCatalog,
  options: ReviewedGradleWrapperOptions = {},
): { distributionSha256Sum: string } {
  if (gradleVersion !== REVIEWED_GRADLE_WRAPPER_VERSION) {
    throw new Error(`Gradle version is not approved for wrapper generation: ${gradleVersion}`);
  }

  const component = catalog.components.find((entry) => entry.id === "org.gradle.distribution");
  if (!component || !component.versions.includes(gradleVersion)) {
    throw new Error(`Gradle version is absent from the reviewed catalog: ${gradleVersion}`);
  }
  if (component.install.kind !== "verified_archive") {
    throw new Error("Reviewed Gradle catalog entry is not a verified archive.");
  }
  const expectedUrl = `https://services.gradle.org/distributions/gradle-${gradleVersion}-bin.zip`;
  if (component.install.url !== expectedUrl || !/^[0-9a-f]{64}$/i.test(component.install.sha256)) {
    throw new Error("Reviewed Gradle distribution source or checksum is invalid.");
  }

  const assetsRoot = options.assetsRoot ?? path.resolve(
    process.cwd(),
    "assets",
    "gradle-wrapper",
    REVIEWED_GRADLE_WRAPPER_VERSION,
  );
  const verifiedAssets = REVIEWED_FILES.map((asset) => {
    const source = path.join(assetsRoot, asset.source);
    const content = fs.readFileSync(source);
    if (content.length !== asset.size || sha256(content) !== asset.sha256) {
      throw new Error(`Reviewed Gradle wrapper asset failed verification: ${asset.source}`);
    }
    return { asset, content };
  });
  for (const { asset, content } of verifiedAssets) {
    const destination = path.join(stagingDir, asset.destination);
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, content, { mode: asset.source === "gradlew" ? 0o755 : 0o600 });
  }
  try {
    fs.chmodSync(path.join(stagingDir, "gradlew"), 0o755);
  } catch {
    // Windows does not expose POSIX execute bits; byte verification remains authoritative.
  }

  return { distributionSha256Sum: component.install.sha256.toLowerCase() };
}
