#Requires -Version 5.1
<#
.SYNOPSIS
Real Windows/Android development environment acceptance runner.

.DESCRIPTION
The default Inspect mode is read-only. It checks /health, initializes MCP,
lists exactly 30 unique tools, inspects all development targets, and verifies
the broker summary without applying plans, creating projects, or starting a
device.

Read-only invocation: test-real-development-environment.bat -Mode Inspect

Android, Windows, and All modes require -ConfirmRealChanges and a new,
explicit disposable -Root. The runner creates an ownership marker, accepts
only the MCP approval prompts generated by its own exact requests, polls every
background task, drains redacted logs by cursor, and removes only the marked
root in a finally block. Credentials and owner identity are read from process
environment variables and never printed or persisted in the report.
#>
[CmdletBinding()]
param(
    [ValidateSet("Inspect", "Android", "Windows", "All")]
    [string]$Mode = "Inspect",
    [switch]$ConfirmRealChanges,
    [string]$Root = "",
    [string]$BaseUrl = "http://127.0.0.1:3000"
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"
$script:RpcId = 0
$script:CurrentStep = "preflight"
$script:CreatedRoot = $false
$script:RootMarker = $null
$script:RootFullPath = $null
$script:Steps = New-Object System.Collections.ArrayList
$script:LongRunningTasks = New-Object System.Collections.ArrayList
$terminalStates = @("succeeded", "failed", "cancelled", "interrupted")

# Transport/authentication values are process-local references. Never echo.
$authToken = [Environment]::GetEnvironmentVariable("MCP_AUTH_TOKEN", "Process")
$ownerId = [Environment]::GetEnvironmentVariable("OWNER_USER_ID", "Process")
$authPin = [Environment]::GetEnvironmentVariable("AUTH_PIN", "Process")
$identityHeader = [Environment]::GetEnvironmentVariable("AUTH_USER_HEADER", "Process")
if ([string]::IsNullOrWhiteSpace($identityHeader)) { $identityHeader = "x-aily-user" }
if ([string]::IsNullOrWhiteSpace($authToken)) { throw "MCP_AUTH_TOKEN must be set in the environment." }
if ([string]::IsNullOrWhiteSpace($ownerId)) { throw "OWNER_USER_ID must be set in the environment." }

function Add-StepResult([string]$Name, [string]$State, [int64]$DurationMs, [string]$Evidence = "") {
    [void]$script:Steps.Add([pscustomobject]@{
        name = $Name
        state = $State
        durationMs = $DurationMs
        evidence = $Evidence
    })
}

function Get-TaskLabel([string]$TaskId) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($TaskId)
        $digest = $sha.ComputeHash($bytes)
        return "task-" + ([BitConverter]::ToString($digest).Replace("-", "").ToLowerInvariant().Substring(0, 12))
    } finally {
        $sha.Dispose()
    }
}

function Get-McpHeaders([string]$Method, [string]$ToolName = "") {
    $headers = @{
        Authorization = "Bearer $authToken"
        Accept = "application/json, text/event-stream"
        "Content-Type" = "application/json"
        "ngrok-skip-browser-warning" = "true"
    }
    # MCP initialize negotiates the protocol before modern transport metadata
    # is valid. Keep modern transport headers on post-initialize requests.
    if ($Method -ne "initialize") {
        $headers["mcp-protocol-version"] = "2026-07-28"
        $headers["mcp-method"] = $Method
    }
    $headers[$identityHeader] = $ownerId
    if (-not [string]::IsNullOrWhiteSpace($ToolName)) { $headers["mcp-name"] = $ToolName }
    return $headers
}

function ConvertFrom-McpPayload([string]$Content) {
    foreach ($line in ($Content -split "`r?`n")) {
        if ($line.StartsWith("data:")) {
            return ($line.Substring(5).Trim() | ConvertFrom-Json)
        }
    }
    return ($Content | ConvertFrom-Json)
}

function Invoke-McpRpc([string]$Method, $Params, [string]$ToolName = "") {
    $script:RpcId++
    if ($Method -ne "initialize" -and -not $Params.ContainsKey("_meta")) {
        $Params = @{} + $Params
        $Params["_meta"] = Get-ToolMeta
    }
    $payload = @{ jsonrpc = "2.0"; id = $script:RpcId; method = $Method; params = $Params }
    $response = Invoke-WebRequest -UseBasicParsing -Uri "$BaseUrl/mcp" -Method Post `
        -Headers (Get-McpHeaders $Method $ToolName) `
        -Body ($payload | ConvertTo-Json -Compress -Depth 32)
    $rpc = ConvertFrom-McpPayload ([string]$response.Content)
    if ($null -ne $rpc.error) { throw "MCP request failed with JSON-RPC code $($rpc.error.code)." }
    return $rpc.result
}

function Get-ToolMeta {
    return @{
        "io.modelcontextprotocol/protocolVersion" = "2026-07-28"
        "io.modelcontextprotocol/clientCapabilities" = @{ elicitation = @{ form = @{} } }
        "io.modelcontextprotocol/clientInfo" = @{ name = "development-acceptance"; version = "1.0.0" }
    }
}

function Invoke-McpToolRaw([string]$Name, $Arguments, $RequestState = $null, $InputResponses = $null) {
    $params = @{ name = $Name; arguments = $Arguments; _meta = Get-ToolMeta }
    if ($null -ne $RequestState) { $params.requestState = $RequestState }
    if ($null -ne $InputResponses) { $params.inputResponses = $InputResponses }
    return Invoke-McpRpc "tools/call" $params $Name
}

function ConvertFrom-ToolResult($Result, [string]$Name) {
    if ($null -eq $Result.content -or $Result.content.Count -lt 1) {
        throw "$Name returned no tool content."
    }
    $body = [string]$Result.content[0].text | ConvertFrom-Json
    if ($body.ok -ne $true) {
        $code = if ($body.code) { [string]$body.code } else { "UNKNOWN" }
        throw "$Name failed with code $code."
    }
    return $body
}

function Invoke-McpTool([string]$Name, $Arguments) {
    return ConvertFrom-ToolResult (Invoke-McpToolRaw $Name $Arguments) $Name
}

function Invoke-ApprovedMcpTool([string]$Name, $Arguments) {
    $result = Invoke-McpToolRaw $Name $Arguments
    for ($round = 0; $round -lt 4 -and $result.resultType -eq "input_required"; $round++) {
        if ($null -eq $result.requestState) { throw "$Name approval omitted request state." }
        $decision = @{ approval = @{ action = "accept"; content = @{ decision = "allow_once" } } }
        $result = Invoke-McpToolRaw $Name $Arguments $result.requestState $decision
    }
    if ($result.resultType -eq "input_required") { throw "$Name exceeded the approval round limit." }
    return ConvertFrom-ToolResult $result $Name
}

function Read-TaskLogs([string]$TaskId) {
    [int64]$stdoutCursor = 0
    [int64]$stderrCursor = 0
    $stdout = New-Object System.Text.StringBuilder
    $stderr = New-Object System.Text.StringBuilder
    for ($page = 0; $page -lt 64; $page++) {
        $logs = Invoke-McpTool "read_development_task_logs" @{
            taskId = $TaskId
            stream = "both"
            cursorStdout = $stdoutCursor
            cursorStderr = $stderrCursor
            maxBytes = 65536
            maxLines = 500
        }
        [void]$stdout.Append([string]$logs.stdout)
        [void]$stderr.Append([string]$logs.stderr)
        $nextStdout = [int64]$logs.nextCursors.stdout
        $nextStderr = [int64]$logs.nextCursors.stderr
        $done = ($logs.eof.stdout -eq $true -and $logs.eof.stderr -eq $true)
        if ($done) { break }
        if ($nextStdout -eq $stdoutCursor -and $nextStderr -eq $stderrCursor) { break }
        $stdoutCursor = $nextStdout
        $stderrCursor = $nextStderr
    }
    return [pscustomobject]@{
        stdout = $stdout.ToString()
        stderr = $stderr.ToString()
        bytes = [System.Text.Encoding]::UTF8.GetByteCount($stdout.ToString() + $stderr.ToString())
    }
}

function Wait-Task([string]$TaskId, [int]$TimeoutSeconds = 7200, [switch]$AllowRunning) {
    $deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    do {
        $status = Invoke-McpTool "get_development_task" @{ taskId = $TaskId }
        $state = [string]$status.task.state
        if ($AllowRunning -and $state -eq "running") {
            return [pscustomobject]@{ task = $status.task; logs = $null }
        }
        if ($terminalStates -contains $state) {
            $logs = Read-TaskLogs $TaskId
            return [pscustomobject]@{ task = $status.task; logs = $logs }
        }
        Start-Sleep -Seconds 1
    } while ([DateTime]::UtcNow -lt $deadline)
    throw "Development task timed out."
}

function Invoke-TaskStep([string]$Name, [string]$Tool, $Arguments, [int]$TimeoutSeconds = 7200) {
    $script:CurrentStep = $Name
    $watch = [System.Diagnostics.Stopwatch]::StartNew()
    $queued = Invoke-ApprovedMcpTool $Tool $Arguments
    if ([string]::IsNullOrWhiteSpace([string]$queued.taskId)) { throw "$Name did not enqueue a task." }
    $done = Wait-Task ([string]$queued.taskId) $TimeoutSeconds
    $watch.Stop()
    if ($done.task.state -ne "succeeded") { throw "$Name task did not succeed." }
    $label = Get-TaskLabel ([string]$queued.taskId)
    Add-StepResult $Name "passed" $watch.ElapsedMilliseconds "$label; logBytes=$($done.logs.bytes)"
    return $done
}

function Start-LongTask([string]$Name, [string]$Tool, $Arguments, [int]$TimeoutSeconds = 120) {
    $script:CurrentStep = $Name
    $watch = [System.Diagnostics.Stopwatch]::StartNew()
    $queued = Invoke-ApprovedMcpTool $Tool $Arguments
    if ([string]::IsNullOrWhiteSpace([string]$queued.taskId)) { throw "$Name did not enqueue a task." }
    [void]$script:LongRunningTasks.Add([string]$queued.taskId)
    $running = Wait-Task ([string]$queued.taskId) $TimeoutSeconds -AllowRunning
    $watch.Stop()
    if ($running.task.state -notin @("running", "succeeded")) { throw "$Name task did not start." }
    Add-StepResult $Name "passed" $watch.ElapsedMilliseconds (Get-TaskLabel ([string]$queued.taskId))
    return [string]$queued.taskId
}

function Stop-TaskOwnedArtifact([string]$TaskId, [string]$Name) {
    $script:CurrentStep = $Name
    $result = Invoke-McpTool "windows_development" @{ action = "stop"; taskId = $TaskId }
    if ($result.ok -ne $true) { throw "$Name failed." }
    $done = Wait-Task $TaskId 120
    if ($done.task.state -notin @("cancelled", "succeeded")) { throw "$Name did not reach a terminal state." }
    [void]$script:LongRunningTasks.Remove($TaskId)
    Add-StepResult $Name "passed" 0 (Get-TaskLabel $TaskId)
}

function Stop-RemainingLongTasks {
    foreach ($taskId in @($script:LongRunningTasks)) {
        try {
            [void](Invoke-McpTool "cancel_development_task" @{ taskId = $taskId })
            [void](Wait-Task $taskId 180)
        } catch {
            # Best-effort cleanup continues for every task. The main acceptance
            # result remains failed and no raw id or exception is emitted.
        } finally {
            [void]$script:LongRunningTasks.Remove($taskId)
        }
    }
}

function Initialize-AcceptanceClient {
    $script:CurrentStep = "initialize"
    $health = Invoke-RestMethod -Uri "$BaseUrl/health" -Method Get `
        -Headers @{ "ngrok-skip-browser-warning" = "true" }
    if ($health.toolCount -ne 30 -or @($health.tools).Count -ne 30) { throw "Health did not report 30 tools." }
    if (@($health.tools | Select-Object -Unique).Count -ne 30) { throw "Health tool inventory contains duplicates." }
    [void](Invoke-McpRpc "initialize" @{
        protocolVersion = "2025-06-18"
        capabilities = @{ elicitation = @{ form = @{} } }
        clientInfo = @{ name = "development-acceptance"; version = "1.0.0" }
    })
    if ($health.authMode -eq "pin") {
        if ([string]::IsNullOrWhiteSpace($authPin)) { throw "AUTH_PIN is required for pin-mode acceptance." }
        [void](Invoke-McpTool "auth" @{ pin = $authPin })
    }
    $listed = Invoke-McpRpc "tools/list" @{}
    $names = @($listed.tools | ForEach-Object { $_.name })
    if ($names.Count -ne 30 -or @($names | Select-Object -Unique).Count -ne 30) {
        throw "MCP tools/list did not return exactly 30 unique tools."
    }
    return $health
}

function Initialize-DisposableRoot {
    if (-not $ConfirmRealChanges) { throw "Real changes require -ConfirmRealChanges and an explicit non-Inspect mode." }
    if ([string]::IsNullOrWhiteSpace($Root) -or -not [System.IO.Path]::IsPathRooted($Root)) {
        throw "-Root must be an explicit absolute disposable directory."
    }
    $full = [System.IO.Path]::GetFullPath($Root).TrimEnd('\', '/')
    $volume = [System.IO.Path]::GetPathRoot($full).TrimEnd('\', '/')
    if ([string]::IsNullOrWhiteSpace($full) -or $full -eq $volume) { throw "A volume root cannot be used as the disposable root." }
    if (Test-Path -LiteralPath $full) { throw "The disposable root must not already exist." }
    $parent = Split-Path -Parent $full
    if (-not (Test-Path -LiteralPath $parent -PathType Container)) { throw "The disposable root parent does not exist." }
    [System.IO.Directory]::CreateDirectory($full) | Out-Null
    $script:RootFullPath = [System.IO.Path]::GetFullPath((Resolve-Path -LiteralPath $full).Path)
    $script:RootMarker = [guid]::NewGuid().ToString("N")
    [System.IO.File]::WriteAllText((Join-Path $script:RootFullPath ".feishu-mcp-acceptance-root"), $script:RootMarker)
    $script:CreatedRoot = $true
    [System.IO.Directory]::CreateDirectory((Join-Path $script:RootFullPath "reports")) | Out-Null
}

function Remove-DisposableRoot {
    if (-not $script:CreatedRoot -or [string]::IsNullOrWhiteSpace($script:RootFullPath)) { return }
    $markerPath = Join-Path $script:RootFullPath ".feishu-mcp-acceptance-root"
    if (-not (Test-Path -LiteralPath $markerPath -PathType Leaf)) { throw "Disposable-root ownership marker is missing; cleanup refused." }
    $marker = [System.IO.File]::ReadAllText($markerPath)
    if ($marker -ne $script:RootMarker) { throw "Disposable-root ownership marker changed; cleanup refused." }
    Remove-Item -LiteralPath $script:RootFullPath -Recurse -Force
    $script:CreatedRoot = $false
}

function Get-FirstArtifactPath($TaskResult, [string]$Extension) {
    foreach ($artifact in @($TaskResult.task.artifacts)) {
        if ($artifact.name -like "*$Extension" -and -not [string]::IsNullOrWhiteSpace([string]$artifact.path)) {
            return [string]$artifact.path
        }
    }
    throw "Expected authorized artifact path was not returned."
}

function Run-InspectAcceptance {
    $watch = [System.Diagnostics.Stopwatch]::StartNew()
    $health = Initialize-AcceptanceClient
    $inspection = Invoke-McpTool "inspect_development_environment" @{
        targets = @("android", "dotnet", "native", "electron")
    }
    if ($inspection.catalogVersion -lt 1 -or @($inspection.components).Count -lt 1) {
        throw "Development environment inspection returned no components."
    }
    if ([string]::IsNullOrWhiteSpace([string]$health.developmentEnvironment.brokerState)) {
        throw "Health omitted broker state."
    }
    $watch.Stop()
    Add-StepResult "read-only-inspection" "passed" $watch.ElapsedMilliseconds `
        "tools=30; targets=4; broker=$($health.developmentEnvironment.brokerState)"
}

function Run-AndroidAcceptance {
    $androidRoot = Join-Path $script:RootFullPath "android"
    [System.IO.Directory]::CreateDirectory($androidRoot) | Out-Null
    $projectRoot = Join-Path $androidRoot "AcceptanceApp"
    $createWatch = [System.Diagnostics.Stopwatch]::StartNew()
    $created = Invoke-ApprovedMcpTool "manage_development_project" @{
        action = "create"; ecosystem = "android"; templateId = "kotlin-basic"
        projectName = "AcceptanceApp"; packageId = "com.example.acceptance"; destination = $projectRoot
        profile = @{ compileSdk = 35; minSdk = 24; targetSdk = 35; agp = "8.7.3"; kotlin = "2.0.21"; gradle = "8.10.2" }
    }
    $createWatch.Stop()
    if ($created.fileCount -lt 1) { throw "Android project creation returned no files." }
    Add-StepResult "android-project-create" "passed" $createWatch.ElapsedMilliseconds "reviewed-template"

    $apkTask = Invoke-TaskStep "android-apk-build" "android_development" @{
        action = "build"; root = $projectRoot; module = "app"; variant = "debug"
    }
    [void](Invoke-TaskStep "android-aab-build" "android_development" @{
        action = "bundle"; root = $projectRoot; module = "app"; variant = "release"
    })
    [void](Invoke-TaskStep "android-unit-test" "android_development" @{
        action = "test_unit"; root = $projectRoot; module = "app"; variant = "debug"
    })
    $apk = Get-FirstArtifactPath $apkTask ".apk"

    $avdName = "FeishuMcpAcceptanceApi35"
    $avds = Invoke-McpTool "android_development" @{ action = "list_avds" }
    $preexistingAvd = @($avds.avds | Where-Object { $_.name -eq $avdName }).Count -gt 0
    if (-not $preexistingAvd) {
        [void](Invoke-TaskStep "android-avd-create" "android_development" @{
            action = "avd_create"; avdName = $avdName
            packageId = "system-images;android-35;google_apis;x86_64"; device = "pixel_6"
        })
    } else {
        Add-StepResult "android-avd-select" "passed" 0 "preexisting-avd-preserved"
    }

    $serial = "emulator-5556"
    $emulatorTask = Start-LongTask "android-emulator-start" "android_development" @{
        action = "emulator_start"; avdName = $avdName; port = 5556
    } 180
    try {
        $booted = $false
        for ($attempt = 0; $attempt -lt 60 -and -not $booted; $attempt++) {
            $devices = Invoke-McpTool "android_development" @{ action = "list_devices" }
            if (@($devices.devices | Where-Object { $_.serial -eq $serial -and $_.state -eq "device" }).Count -gt 0) {
                $probe = Invoke-TaskStep "android-boot-probe" "android_development" @{
                    action = "diagnostic"; serial = $serial; diagnostic = "getprop_subset"
                } 120
                $props = [string]$probe.logs.stdout
                $booted = ($props -match '\[sys\.boot_completed\]:\s*\[1\]' -and $props -match '\[dev\.bootcomplete\]:\s*\[1\]')
            }
            if (-not $booted) { Start-Sleep -Seconds 2 }
        }
        if (-not $booted) { throw "Android emulator did not report both boot-complete properties." }

        [void](Invoke-TaskStep "android-install" "android_development" @{ action = "install"; serial = $serial; hostApk = $apk })
        [void](Invoke-TaskStep "android-start-app" "android_development" @{
            action = "start_app"; serial = $serial; packageId = "com.example.acceptance"; activity = ".MainActivity"
        })
        $pidTask = Invoke-TaskStep "android-app-pid" "android_development" @{
            action = "diagnostic"; serial = $serial; diagnostic = "pidof_package"; packageId = "com.example.acceptance"
        }
        $pidText = ([string]$pidTask.logs.stdout).Trim()
        if ($pidText -notmatch '^\d+$') { throw "Android package pid was not available." }
        [void](Invoke-TaskStep "android-logcat" "android_development" @{
            action = "logcat"; serial = $serial; pid = [int]$pidText
        })
        $screenshot = Join-Path $androidRoot "acceptance.png"
        [void](Invoke-TaskStep "android-screenshot" "android_development" @{
            action = "screenshot"; serial = $serial; hostPng = $screenshot
        })
        $transfer = Join-Path $androidRoot "transfer.txt"
        [System.IO.File]::WriteAllText($transfer, "feishu-mcp acceptance")
        [void](Invoke-TaskStep "android-push" "android_development" @{
            action = "push"; serial = $serial; hostFile = $transfer; deviceFile = "/sdcard/Download/feishu-mcp-acceptance.txt"
        })
        [void](Invoke-TaskStep "android-pull" "android_development" @{
            action = "pull"; serial = $serial; deviceFile = "/sdcard/Download/feishu-mcp-acceptance.txt"
            hostFile = (Join-Path $androidRoot "transfer-returned.txt")
        })
        [void](Invoke-TaskStep "android-loopback-forward" "android_development" @{
            action = "forward"; serial = $serial; localPort = 38555; remoteSpec = "tcp:38555"
        })
        [void](Invoke-TaskStep "android-force-stop" "android_development" @{
            action = "force_stop"; serial = $serial; packageId = "com.example.acceptance"
        })
        [void](Invoke-TaskStep "android-clear" "android_development" @{
            action = "clear"; serial = $serial; packageId = "com.example.acceptance"
        })
        [void](Invoke-TaskStep "android-uninstall" "android_development" @{
            action = "uninstall"; serial = $serial; packageId = "com.example.acceptance"
        })

        $keystorePath = [Environment]::GetEnvironmentVariable("FEISHU_MCP_ACCEPTANCE_ANDROID_KEYSTORE", "Process")
        $ksAlias = [Environment]::GetEnvironmentVariable("FEISHU_MCP_ACCEPTANCE_ANDROID_KEY_ALIAS", "Process")
        $ksCredential = [Environment]::GetEnvironmentVariable("FEISHU_MCP_ACCEPTANCE_ANDROID_KEYSTORE_CREDENTIAL_ID", "Process")
        $keyCredential = [Environment]::GetEnvironmentVariable("FEISHU_MCP_ACCEPTANCE_ANDROID_KEY_CREDENTIAL_ID", "Process")
        $missingAndroidCredentialRefs = @(
            @($keystorePath, $ksAlias, $ksCredential, $keyCredential) |
                Where-Object { [string]::IsNullOrWhiteSpace($_) }
        )
        if ($missingAndroidCredentialRefs.Count -gt 0) {
            throw "Android acceptance credential references are incomplete."
        }
        $signedApk = Join-Path $androidRoot "acceptance-signed.apk"
        [void](Invoke-TaskStep "android-sign" "android_development" @{
            action = "sign"; inApk = $apk; outApk = $signedApk; keystore = $keystorePath
            ksAlias = $ksAlias; ksCredentialId = $ksCredential; keyCredentialId = $keyCredential
        })
        [void](Invoke-TaskStep "android-verify" "android_development" @{ action = "verify"; inApk = $signedApk })
    } finally {
        try {
            [void](Invoke-TaskStep "android-emulator-stop" "android_development" @{ action = "emulator_stop"; serial = $serial } 120)
        } finally {
            $emulatorFinal = Wait-Task $emulatorTask 180
            if ($emulatorFinal.task.state -notin @("succeeded", "cancelled")) { throw "Task-owned emulator process did not terminate." }
            [void]$script:LongRunningTasks.Remove($emulatorTask)
        }
    }
}

function New-CommonProjectProfile {
    return @{ compileSdk = 35; minSdk = 24; targetSdk = 35; agp = "8.7.3"; kotlin = "2.0.21"; gradle = "8.10.2" }
}

function Create-WindowsProject([string]$Ecosystem, [string]$TemplateId, [string]$ProjectName, [string]$Destination, $Profile) {
    $watch = [System.Diagnostics.Stopwatch]::StartNew()
    $created = Invoke-ApprovedMcpTool "manage_development_project" @{
        action = "create"; ecosystem = $Ecosystem; templateId = $TemplateId
        projectName = $ProjectName; packageId = "com.example.$($Ecosystem)acceptance"
        destination = $Destination; profile = $Profile
    }
    $watch.Stop()
    if ($created.fileCount -lt 1) { throw "$Ecosystem project creation returned no files." }
    Add-StepResult "windows-$Ecosystem-project-create" "passed" $watch.ElapsedMilliseconds "reviewed-template"
}

function Run-WindowsAcceptance {
    $windowsRoot = Join-Path $script:RootFullPath "windows"
    [System.IO.Directory]::CreateDirectory($windowsRoot) | Out-Null
    $dotnetRoot = Join-Path $windowsRoot "dotnet"
    $nativeRoot = Join-Path $windowsRoot "native"
    $electronRoot = Join-Path $windowsRoot "electron"

    $dotnetProfile = New-CommonProjectProfile
    $dotnetProfile.framework = "net8.0"; $dotnetProfile.configuration = "Release"; $dotnetProfile.platform = "AnyCPU"
    Create-WindowsProject "dotnet" "console" "AcceptanceDotnet" $dotnetRoot $dotnetProfile
    $nativeProfile = New-CommonProjectProfile
    $nativeProfile.cppStandard = "20"; $nativeProfile.buildType = "executable"; $nativeProfile.withTests = $true
    Create-WindowsProject "native" "native-basic" "AcceptanceNative" $nativeRoot $nativeProfile
    $electronProfile = New-CommonProjectProfile
    $electronProfile.packageManager = "npm"
    Create-WindowsProject "electron" "electron-basic" "acceptance-electron" $electronRoot $electronProfile

    [void](Invoke-TaskStep "dotnet-restore" "windows_development" @{
        action = "dotnet_restore"; root = $dotnetRoot; projectOrSolution = "AcceptanceDotnet.csproj"; configuration = "Release"; framework = "net8.0"
    })
    [void](Invoke-TaskStep "dotnet-build" "windows_development" @{
        action = "dotnet_build"; root = $dotnetRoot; projectOrSolution = "AcceptanceDotnet.csproj"; configuration = "Release"; framework = "net8.0"
    })
    [void](Invoke-TaskStep "dotnet-test" "windows_development" @{
        action = "dotnet_test"; root = $dotnetRoot; projectOrSolution = "AcceptanceDotnet.csproj"; configuration = "Release"; framework = "net8.0"
    })
    $publish = Invoke-TaskStep "dotnet-publish" "windows_development" @{
        action = "dotnet_publish"; root = $dotnetRoot; projectOrSolution = "AcceptanceDotnet.csproj"; configuration = "Release"; framework = "net8.0"; runtime = "win-x64"
    }
    [void](Invoke-TaskStep "dotnet-pack" "windows_development" @{
        action = "dotnet_pack"; root = $dotnetRoot; projectOrSolution = "AcceptanceDotnet.csproj"; configuration = "Release"
    })

    [void](Invoke-TaskStep "native-configure" "windows_development" @{
        action = "native_configure"; root = $nativeRoot; sourceDir = $nativeRoot
        buildDir = (Join-Path $nativeRoot "build"); preset = "msvc-release"; configuration = "Release"
    })
    [void](Invoke-TaskStep "native-build" "windows_development" @{
        action = "native_build"; root = $nativeRoot; buildDir = (Join-Path $nativeRoot "build")
        configuration = "Release"; target = "AcceptanceNative"
    })
    [void](Invoke-TaskStep "native-test" "windows_development" @{
        action = "native_test"; root = $nativeRoot; buildDir = (Join-Path $nativeRoot "build"); configuration = "Release"
    })
    [void](Invoke-TaskStep "native-package" "windows_development" @{
        action = "native_package"; root = $nativeRoot; buildDir = (Join-Path $nativeRoot "build"); configuration = "Release"
    })

    [void](Invoke-TaskStep "electron-install" "windows_development" @{ action = "electron_install"; root = $electronRoot })
    [void](Invoke-TaskStep "electron-test" "windows_development" @{
        action = "electron_test"; root = $electronRoot; scriptName = "test"
    })
    [void](Invoke-TaskStep "electron-package" "windows_development" @{
        action = "electron_package"; root = $electronRoot; scriptName = "package"
    })

    $inspection = Invoke-McpTool "inspect_development_environment" @{ targets = @("dotnet", "native", "electron") }
    $requiredInspection = @(
        "microsoft.visualstudio.2022.buildtools",
        "microsoft.visualstudio.workload.manageddesktop",
        "microsoft.visualstudio.workload.nativedesktop"
    )
    foreach ($componentId in $requiredInspection) {
        if (@($inspection.components | Where-Object { $_.componentId -eq $componentId }).Count -ne 1) {
            throw "Windows workload inspection omitted a required reviewed component."
        }
    }
    Add-StepResult "windows-workload-inspection" "passed" 0 "reviewed-components-present"

    $runnable = Get-FirstArtifactPath $publish ".exe"
    $runTask = Start-LongTask "windows-run-artifact" "windows_development" @{
        action = "run"; artifactPath = $runnable; cwd = (Split-Path -Parent $runnable)
    } 120
    Stop-TaskOwnedArtifact $runTask "windows-stop-artifact"

    $missingCredential = Invoke-McpToolRaw "windows_development" @{
        action = "sign"; inFile = $runnable; outFile = (Join-Path $windowsRoot "missing-credential.exe")
        credentialId = "00000000-0000-4000-8000-000000000000"; timestampOrigin = "http://timestamp.digicert.com"
    }
    $missingBody = [string]$missingCredential.content[0].text | ConvertFrom-Json
    if ($missingBody.ok -ne $false -or $missingBody.code -ne "WINDOWS_CREDENTIAL_UNKNOWN") {
        throw "Windows missing-credential behavior was not enforced."
    }
    Add-StepResult "windows-missing-credential" "passed" 0 "stable-error"

    $windowsCredential = [Environment]::GetEnvironmentVariable("FEISHU_MCP_ACCEPTANCE_WINDOWS_CREDENTIAL_ID", "Process")
    $timestampOrigin = [Environment]::GetEnvironmentVariable("FEISHU_MCP_ACCEPTANCE_WINDOWS_TIMESTAMP_ORIGIN", "Process")
    if ([string]::IsNullOrWhiteSpace($windowsCredential) -or [string]::IsNullOrWhiteSpace($timestampOrigin)) {
        throw "Windows acceptance credential references are incomplete."
    }
    $signed = Join-Path $windowsRoot "acceptance-signed.exe"
    [void](Invoke-TaskStep "windows-sign" "windows_development" @{
        action = "sign"; inFile = $runnable; outFile = $signed
        credentialId = $windowsCredential; timestampOrigin = $timestampOrigin
    })
    [void](Invoke-TaskStep "windows-verify" "windows_development" @{ action = "verify"; inFile = $signed })
}

function Write-RedactedSummary([string]$FinalState) {
    $summary = [pscustomobject]@{
        mode = $Mode
        state = $FinalState
        stepCount = $script:Steps.Count
        totalDurationMs = [int64](($script:Steps | Measure-Object -Property durationMs -Sum).Sum)
        steps = @($script:Steps)
    }
    # The summary contains no paths, owner id, raw task ids, device serial,
    # credential ids, or secrets. In real mode it is written only inside the
    # marked disposable root, then emitted before confined cleanup.
    $json = $summary | ConvertTo-Json -Depth 8
    if ($script:CreatedRoot) {
        [System.IO.File]::WriteAllText((Join-Path $script:RootFullPath "reports\acceptance-summary.json"), $json)
    }
    Write-Output $json
}

$failed = $false
try {
    if ($Mode -eq "Inspect") {
        Run-InspectAcceptance
    } else {
        Initialize-DisposableRoot
        [void](Initialize-AcceptanceClient)
        if ($Mode -in @("Android", "All")) { Run-AndroidAcceptance }
        if ($Mode -in @("Windows", "All")) { Run-WindowsAcceptance }
    }
    Write-RedactedSummary "passed"
} catch {
    $failed = $true
    Add-StepResult $script:CurrentStep "failed" 0 "redacted-error"
    Write-RedactedSummary "failed"
    Write-Error "Acceptance failed at a redacted step. Review the local server/task logs."
} finally {
    if ($script:LongRunningTasks.Count -gt 0) {
        Stop-RemainingLongTasks
    }
    if ($Mode -ne "Inspect" -and $script:CreatedRoot) {
        Remove-DisposableRoot
    }
}

if ($failed) { exit 1 }
